networks:
  ramses-sas-net:
    driver: bridge
    name: ramses-sas-net

services:
  mysql:
    image: giamburrasca/mysql:${ARCH}
    container_name: mysql
    restart: always
    networks:
      - ramses-sas-net
    ports:
      - "53306:3306"

  sefa-eureka:
    image: giamburrasca/sefa-eureka:${ARCH}
    container_name: sefa-eureka
    restart: always
    networks:
      - ramses-sas-net
    ports:
      - "58082:58082"

  sefa-configserver:
    image: giamburrasca/sefa-configserver:${ARCH}
    container_name: sefa-configserver
    environment:
      GITHUB_REPOSITORY_URL: ${GITHUB_REPOSITORY_URL}
      GITHUB_OAUTH: ${GITHUB_OAUTH}
    restart: always
    networks:
      - ramses-sas-net
    depends_on:
      - sefa-eureka
    ports:
      - "8888:58888"

  sefa-restaurant-service:
    image: giamburrasca/sefa-restaurant-service:${ARCH}
    container_name: sefa-restaurant-service
    restart: always
    networks:
      - ramses-sas-net
    depends_on:
      - sefa-configserver
    ports:
      - "58085:58085"

  sefa-ordering-service:
    image: giamburrasca/sefa-ordering-service:${ARCH}
    container_name: sefa-ordering-service
    restart: always
    networks:
      - ramses-sas-net
    depends_on:
      - sefa-configserver
    ports:
      - "58086:58086"

  sefa-payment-proxy-1-service:
    image: giamburrasca/sefa-payment-proxy-1-service:${ARCH}
    container_name: sefa-payment-proxy-1-service
    restart: always
    networks:
      - ramses-sas-net
    depends_on:
      - sefa-configserver
    ports:
      - "58090:58090"

  sefa-delivery-proxy-1-service:
    image: giamburrasca/sefa-delivery-proxy-1-service:${ARCH}
    container_name: sefa-delivery-proxy-1-service
    restart: always
    networks:
      - ramses-sas-net
    depends_on:
      - sefa-configserver
    ports:
      - "58095:58095"

  sefa-web-service:
    image: giamburrasca/sefa-web-service:${ARCH}
    container_name: sefa-web-service
    restart: always
    networks:
      - ramses-sas-net
    depends_on:
      - sefa-configserver
    ports:
      - "58080:58080"

  sefa-api-gateway:
    image: giamburrasca/sefa-api-gateway:${ARCH}
    container_name: sefa-api-gateway
    restart: always
    networks:
      - ramses-sas-net
    depends_on:
      - sefa-configserver
    ports:
      - "58081:58081"

#  sefa-payment-proxy-2-service:
#    image: giamburrasca/sefa-payment-proxy-2-service:${ARCH}
#    container_name: sefa-payment-proxy-2-service
#    restart: always
#    networks:
#      - ramses-sas-net
#    depends_on:
#      - sefa-configserver
#
#  sefa-delivery-proxy-2-service:
#    image: giamburrasca/sefa-delivery-proxy-2-service:${ARCH}
#    container_name: sefa-delivery-proxy-2-service
#    restart: always
#    networks:
#      - ramses-sas-net
#    depends_on:
#      - sefa-configserver

  sefa-probe:
    image: giamburrasca/sefa-probe:${ARCH}
    container_name: sefa-probe
    restart: always
    networks:
      - ramses-sas-net
    depends_on:
      - sefa-configserver
    ports:
      - "58020:58020"

  sefa-instances-manager:
    image: giamburrasca/sefa-instances-manager:${ARCH}
    container_name: sefa-instances-manager
    restart: always
    networks:
      - ramses-sas-net
    depends_on:
      - sefa-configserver
    ports:
      - "58015:58015"

  sefa-config-manager:
    image: giamburrasca/sefa-config-manager:${ARCH}
    container_name: sefa-config-manager
    environment:
      GITHUB_REPOSITORY_URL: ${GITHUB_REPOSITORY_URL}
      GITHUB_OAUTH: ${GITHUB_OAUTH}
    restart: always
    networks:
      - ramses-sas-net
    depends_on:
      - sefa-configserver
    ports:
      - "58016:58016"

  ramses-knowledge:
    image: giamburrasca/ramses-knowledge:${ARCH}
    container_name: ramses-knowledge
    restart: always
    networks:
      - ramses-sas-net
    ports:
      - "58005:58005"

  ramses-analyse:
    image: giamburrasca/ramses-analyse:${ARCH}
    container_name: ramses-analyse
    restart: always
    networks:
      - ramses-sas-net
    depends_on:
      - ramses-knowledge
    ports:
      - "58002:58002"

  ramses-execute:
    image: giamburrasca/ramses-execute:${ARCH}
    container_name: ramses-execute
    restart: always
    networks:
      - ramses-sas-net
    depends_on:
      - ramses-knowledge
    ports:
      - "58004:58004"

  ramses-monitor:
    image: giamburrasca/ramses-monitor:${ARCH}
    container_name: ramses-monitor
    restart: always
    networks:
      - ramses-sas-net
    depends_on:
      - ramses-knowledge
    ports:
      - "58001:58001"

  ramses-dashboard:
    image: giamburrasca/ramses-dashboard:${ARCH}
    container_name: ramses-dashboard
    restart: always
    networks:
      - ramses-sas-net
    depends_on:
      - ramses-knowledge
    ports:
      - "58000:58000"

  ramses-plan:
#    image: giamburrasca/ramses-plan:${ARCH}
    image: giamburrasca/ramses-plan:arm64
    container_name: ramses-plan
    restart: always
    networks:
      - ramses-sas-net
    depends_on:
      - ramses-knowledge
    ports:
      - "58003:58003"

  simulation-scenario-1:
    image: giamburrasca/scenario1:${ARCH}
    container_name: simulation-scenario-1
    networks:
      - ramses-sas-net
    profiles:
      - simulation