version: '3.8'

services:
  mysql:
    image: giamburrasca/mysql:${ARCH}
    ports:
      - "55000:3306"
      - "55001:33060"
    networks:
      - ramses-sas-net
    restart: always

  sefa-eureka:
    image: giamburrasca/sefa-eureka:${ARCH}
    ports:
      - "55002:58082"
    networks:
      - ramses-sas-net
    restart: always

  sefa-configserver:
    image: giamburrasca/sefa-configserver:${ARCH}
    ports:
      - "55003:58888"
    environment:
      GITHUB_REPOSITORY_URL: ${GITHUB_REPOSITORY_URL}
      GITHUB_OAUTH: $(GITHUB_OAUTH)
    networks:
      - ramses-sas-net
    restart: always

  sefa-payment-proxy-1-service:
    image: giamburrasca/sefa-payment-proxy-1-service:${ARCH}
    ports:
      - "55006:58090"
    networks:
      - ramses-sas-net
    restart: always

  sefa-delivery-proxy-1-service:
    image: giamburrasca/sefa-delivery-proxy-1-service:${ARCH}
    ports:
      - "55007:58095"
    networks:
      - ramses-sas-net
    restart: always

  sefa-web-service:
    image: giamburrasca/sefa-web-service:${ARCH}
    ports:
      - "55008:58080"
    networks:
      - ramses-sas-net
    restart: always

  sefa-api-gateway:
    image: giamburrasca/sefa-api-gateway:${ARCH}
    ports:
      - "55009:58081"
    networks:
      - ramses-sas-net
    restart: always

  sefa-probe:
    image: giamburrasca/sefa-probe:${ARCH}
    ports:
      - "55010:58020"
    networks:
      - ramses-sas-net
    restart: always

  sefa-restaurant-service:
    image: giamburrasca/sefa-restaurant-service:${ARCH}
    ports:
      - "55019:58085"
    networks:
      - ramses-sas-net
    restart: always

  sefa-ordering-service:
    image: giamburrasca/sefa-ordering-service:${ARCH}
    ports:
      - "34761:34761"
    networks:
      - ramses-sas-net
    restart: always

  sefa-instances-manager:
    image: giamburrasca/sefa-instances-manager:${ARCH}
    ports:
      - "55011:58015"
    networks:
      - ramses-sas-net
    restart: always

  sefa-config-manager:
    image: giamburrasca/sefa-config-manager:${ARCH}
    ports:
      - "55012:58016"
    environment:
      GITHUB_OAUTH: ${GITHUB_OAUTH}
      GITHUB_REPOSITORY_URL: ${GITHUB_REPOSITORY_URL}
    networks:
      - ramses-sas-net
    restart: always

  ramses-knowledge:
    image: giamburrasca/ramses-knowledge:${ARCH}
    ports:
      - "55013:58005"
    networks:
      - ramses-sas-net
    restart: always

  ramses-analyse:
    image: giamburrasca/ramses-analyse:${ARCH}
    ports:
      - "55014:58002"
    networks:
      - ramses-sas-net
    restart: always

  ramses-execute:
    image: giamburrasca/ramses-execute:${ARCH}
    ports:
      - "55015:58004"
    networks:
      - ramses-sas-net
    restart: always

  ramses-monitor:
    image: giamburrasca/ramses-monitor:${ARCH}
    ports:
      - "55016:58001"
    networks:
      - ramses-sas-net
    restart: always

  ramses-dashboard:
    image: giamburrasca/ramses-dashboard:${ARCH}
    ports:
      - "55017:58000"
    networks:
      - ramses-sas-net
    restart: always

  ramses-plan:
    image: giamburrasca/ramses-plan:${ARCH}
    ports:
      - "55018:58003"
    networks:
      - ramses-sas-net
    restart: always

networks:
  ramses-sas-net:
    driver: bridge
    name: ramses-sas-net  # This will use exactly this name without prefix
 